all:
	gcc trabalho2.c registros.c funcionalidades.c arvoreb.c funcoes_fornecidas.c -std=c99 -Wall -o trabalho2

run:
	./trabalho2

testa:
	valgrind ./trabalho2

zip:
	zip trabalho2.zip funcionalidades.c funcionalidades.h registros.c registros.h funcoes_fornecidas.c funcoes_fornecidas.h arvoreb.c arvoreb.h trabalho2.c Makefile